title: Rails REST Framework
email: schmitgreg@gmail.com
description: Rails REST Framework helps you build awesome Web APIs in Ruby on Rails.
url: "https://rails-rest-framework.com"
collections:
  guide:
    output: true
    permalink: /:collection/:path/

# Build settings
markdown: kramdown
